// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBedBQsejO42SxoHXS2nwa61YLt_bX1YUQ',
    appId: '1:474773003470:web:901f000c227bc82837c49f',
    messagingSenderId: '474773003470',
    projectId: 'synq-task-app',
    authDomain: 'synq-task-app.firebaseapp.com',
    storageBucket: 'synq-task-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlbsFZaHr_tG9T65bULKRuzmhIJhVu20',
    appId: '1:474773003470:android:7c2b412bc39f9b4d37c49f',
    messagingSenderId: '474773003470',
    projectId: 'synq-task-app',
    storageBucket: 'synq-task-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI10dr7PXrqkXGwNgi1yA7z6Irw70HiKk',
    appId: '1:474773003470:ios:d0b387bbda5e6f8d37c49f',
    messagingSenderId: '474773003470',
    projectId: 'synq-task-app',
    storageBucket: 'synq-task-app.firebasestorage.app',
    iosBundleId: 'synq.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI10dr7PXrqkXGwNgi1yA7z6Irw70HiKk',
    appId: '1:474773003470:ios:a01dcad29a58c58537c49f',
    messagingSenderId: '474773003470',
    projectId: 'synq-task-app',
    storageBucket: 'synq-task-app.firebasestorage.app',
    iosBundleId: 'synq1.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBedBQsejO42SxoHXS2nwa61YLt_bX1YUQ',
    appId: '1:474773003470:web:d5f99bda9a0c880837c49f',
    messagingSenderId: '474773003470',
    projectId: 'synq-task-app',
    authDomain: 'synq-task-app.firebaseapp.com',
    storageBucket: 'synq-task-app.firebasestorage.app',
  );
}
